users:
    root: ENC[AES256_GCM,data:X60AZHoldQpwhnfSG86iDa0knsxMmuLbFY6h9ql41UDyZiy3yFZhmjsNevoSyKOsl4zySNgANfKBP0VoHCO43SAlBo+uXK9new==,iv:1Qpbx7ePjGPy6dz5IC4VvipTPfx9KEGKr6jRr0ntr3Y=,tag:2iNzp58mzM6aKTwV6rUAeQ==,type:str]
    yoseio: ENC[AES256_GCM,data:acfpA649ZwOhE8bQ6ikp80iQH2XandeVEPG3sSP4xWAtfQsuR626rXkvusC329HhVk8N4vlavRcz9D3wO9Run4aHAIhEmIXpug==,iv:E2hiA1H1sAaBTATHGJMz0BFKw4fjjkAhpjHT47jx20E=,tag:lG+mh/C6U2BGwIO0i5HImA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mf535dx46jy7pt3xvyzqgl2g4r370rls7unghzds6qsau9wq8qvsnffepl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMmFmMGVwWVpMdG0wTk1L
            dzl2OEkzSDRNV1Y0cVRNbHhVOVBkQWkrd1RjClJJVUd2TFBZSTByR0lDN2M3WjMw
            N2FHeUV2K0dURUFRcTlJM0NRMlhLOE0KLS0tIGpjdGVaU0Y3MHdMSk5JbFNiWDZP
            YUVGcjhaWGNLZ3FjaGdzVW5EQzZQSXMKiCq4hvVCmlpDAeFKo0WZeB3w6TuarPLj
            ZeNvABTSEeqoVbmkZOY4sG2VnwUHSHvQKM8X9jI0KiMWzCaq5tLKww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sqre9wzt6anfg6n3fxqk2649c8zuwp4wcqjy066ksrywxt6l8adsuaaxuc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbjE3SjR5V0RDTHUrY29w
            VHBvWXJhR1dMbHdEVk9wSHFYVVVVT3lFMXdrCkRCTzBkRjZxNWtrTWJod2JVdHhw
            NmtSNDAwdzBoNitob0VXUTlmdlh1UzAKLS0tIENIaVdPWTJGaUJ0TFJ2WDA3MnRa
            T0RKZ3lOWC9uOHUxWTRLN201LytZbFUKI2SW0JCWiaGr30/Wk9YG6FlEfYp4vNIv
            el0A9hWBZyys36GzSRyhiA3WdvS6WBVXYCssJ7XKBVtxEPhC0cERhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T05:48:24Z"
    mac: ENC[AES256_GCM,data:ZYD+jj5B9E/3ZYvRH1kk/2ZH400D3Ts8XmddJNDekVmB4Pk5ETRfoTF8bmmNM0fwPjjwrqmvvQ86y5TIbNlji5d4+29IK9g9VEHj4HG772fb1EgxJ6+Is5T6G/UG6O5FasKZyXwMV0KvNfZB2gwAIimwKid+wtMO1cf/+Rwe+jU=,iv:19dgklLdVuqsfuClSE/VTZ4idcyq+HJyMaQ8TfK/IPg=,tag:cKMZfy4TL9t9tdaK4Mtvrw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
