users:
    root: ENC[AES256_GCM,data:X60AZHoldQpwhnfSG86iDa0knsxMmuLbFY6h9ql41UDyZiy3yFZhmjsNevoSyKOsl4zySNgANfKBP0VoHCO43SAlBo+uXK9new==,iv:1Qpbx7ePjGPy6dz5IC4VvipTPfx9KEGKr6jRr0ntr3Y=,tag:2iNzp58mzM6aKTwV6rUAeQ==,type:str]
    yoseio: ENC[AES256_GCM,data:acfpA649ZwOhE8bQ6ikp80iQH2XandeVEPG3sSP4xWAtfQsuR626rXkvusC329HhVk8N4vlavRcz9D3wO9Run4aHAIhEmIXpug==,iv:E2hiA1H1sAaBTATHGJMz0BFKw4fjjkAhpjHT47jx20E=,tag:lG+mh/C6U2BGwIO0i5HImA==,type:str]
cloudflared: ENC[AES256_GCM,data:O/3c9Y9/GuM/+ZrrJADxNnmzwpT4fKekozkz5IIdbJhZ8/WJ/rvU8LRXdVHnl+tVvhY1pkYL/XP3AaKmMu/W0OL08M5/d6FvKlrvSJWecC1mabmfMQGfCD55VtD5W1lMzOvBPD0QEMofp9os9tzBiUxJt0nd6F7sAn5x1NR35FNTJss34p2RLFR/cTjP+mcTcyQlfUAkGtRLhoK/XH3o+ExcBOUM,iv:C3aSDnABFm+HpYg+VXTsd8So5hIfrQrOLuWEghe2iC4=,tag:zx5njSUaTsJwWRuOChv5xQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mf535dx46jy7pt3xvyzqgl2g4r370rls7unghzds6qsau9wq8qvsnffepl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMmFmMGVwWVpMdG0wTk1L
            dzl2OEkzSDRNV1Y0cVRNbHhVOVBkQWkrd1RjClJJVUd2TFBZSTByR0lDN2M3WjMw
            N2FHeUV2K0dURUFRcTlJM0NRMlhLOE0KLS0tIGpjdGVaU0Y3MHdMSk5JbFNiWDZP
            YUVGcjhaWGNLZ3FjaGdzVW5EQzZQSXMKiCq4hvVCmlpDAeFKo0WZeB3w6TuarPLj
            ZeNvABTSEeqoVbmkZOY4sG2VnwUHSHvQKM8X9jI0KiMWzCaq5tLKww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sqre9wzt6anfg6n3fxqk2649c8zuwp4wcqjy066ksrywxt6l8adsuaaxuc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbjE3SjR5V0RDTHUrY29w
            VHBvWXJhR1dMbHdEVk9wSHFYVVVVT3lFMXdrCkRCTzBkRjZxNWtrTWJod2JVdHhw
            NmtSNDAwdzBoNitob0VXUTlmdlh1UzAKLS0tIENIaVdPWTJGaUJ0TFJ2WDA3MnRa
            T0RKZ3lOWC9uOHUxWTRLN201LytZbFUKI2SW0JCWiaGr30/Wk9YG6FlEfYp4vNIv
            el0A9hWBZyys36GzSRyhiA3WdvS6WBVXYCssJ7XKBVtxEPhC0cERhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T07:35:14Z"
    mac: ENC[AES256_GCM,data:wEUFKI68L+ryGFPa7xFo1+IJw/doN0DGw4DZmjhhr+bKtkh4m+thK0ZE+RSiCIguX8pdG630PoIyTg2wana09HMJowklA/AUcR06D2J+9IuTapSMOaMq96/g4J2Gi0kN8Lkql9zHSrzd6WkVnTLI+St68ecr8+nu8yIVqj9nDds=,iv:nUAfbfLUPLTX0KYUgZSrlZqoQ6o2Ri9fU5vis5AzVeE=,tag:L+7CrquZ1m7Wrdua3lDYyA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
